### ISSUE TITLE
display game money

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#1]
## Value Proposition

As a User
I want to see my game money
so that I know how much I've earned with playing the game

## Description

![Image](https://user-images.githubusercontent.com/109807794/229278536-4cf860c1-5f31-47af-ac65-571d42cb8c85.png)

## Acceptance Critera

- [ ] display a number
- [ ] have a point & comma seperation included
- [ ] display a currency symbol

## Tasks

- [x] write tests
- [x] create a `MoneyDisplay` component
- [x] feed it with the `money` prop as integer
- [x] write point & comma seperation logic function
- [x] fake float value

## Complexity Weight

1
