### ISSUE TITLE
US8 - unlock next tier

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#13]
## Value Proposition

As a user
I want to unlock the next tier
so that I can access additional rewards and benefits

## Description

![Image](https://user-images.githubusercontent.com/109807794/229377467-fa7131da-d494-47c8-9b41-ec8f53b82420.png)

## Acceptance Critera

- [ ] display the next unlockable tiers to the user
- [ ] allow the user to unlock the next tier by pressing on the unlockable content once the required price is reached.
- [ ] remove the "unlock" display after the tier has been unlocked.
- [ ] deduct the cost of unlocking from the user's wallet upon unlocking the feature.
- [ ] make the unlocked tier visible and functional.

## Tasks

- [ ] write tests
- [ ] create a `TierContainer` and a `UnlockTier` component
- [ ] have a boolean state in Zustand, to determine if tier was purchased or not
- [ ] create a fixed price in the Tier array in the Zustand Store
- [ ] if false: `TierContainer` renders `UnlockTier` which is a button, pressing the button, sets boolean true 
- [ ] if true: loads props corresponding to tier 2 scaled values and renders components `moneyButton` `progressBar` `investmentButton` `investmentMilestones` within section, like it was prepared in US7

## Complexity Weight

3

**Comment by JessicaLoers** [comment]
**Hey @Satttoshi** 
Here are some picky suggestions: ✨

_Suggestion to describe the benefit of this feature to the user in a little more detail_
**As a user**
**I want to** unlock the next tier
**so that I can** access additional rewards and benefits

_The AC could be formulated more precisely_
**Acceptance Criteria**
- Show the next unlockable tiers to the user.
- Allow the user to unlock the next tier by pressing on the unlockable content once the required price is reached.
- Remove the "unlock" display after the tier has been unlocked.
- Deduct the cost of unlocking from the user's wallet upon unlocking the feature.
- Make the unlocked tier visible and functional.
