### ISSUE TITLE
US9 - scaling logic

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#15]
## Value Proposition

As a gamer
I want to enjoy a more rewarding and engaging experience through meaningful scaling
so that each unlocked tier offers equal benefits and allows me to progress fairly and enjoyably through the game

## Description

![Image](https://user-images.githubusercontent.com/109807794/230086975-5383a51f-4c30-4386-b22c-a6d24d73a676.png)

## Acceptance Critera

- [ ] the "invest" button scales price and income meaningfully based on tier level and relevant factors
- [ ] investing in a different tier maintains a fair relation to the previous tier's scaling

(hint/help for QA: each Product (wordpress, react, nextjs) is a tier, going from low to high)

## Tasks

- [ ] write tests
- [ ] implement a logic to handle floating point values, so multiplying floats work and getting displayed correctly in `moneyDisplay`
- [ ] add scaling relations to the current tiers array in the Zustand store
- [ ] accumulate scaling values by multiplication and division instead of addition and subtraction

## Complexity Weight

3

**Comment by FrankSiyli** [comment]
LGTM as a non-gamer👍
