### ISSUE TITLE
US10 - popup text

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#17]
## Value Proposition

As a user
I want visual feedback on my income increase when I invest
so I can make informed decisions and feel more dopamine

## Description

![Image](https://user-images.githubusercontent.com/109807794/230293497-23005170-6411-4388-b115-2ca83038c9cf.png)

## Acceptance Critera

- [ ] A popup should show the income increase when the "Invest" button is clicked.
- [ ] The popup should display the updated income
- [ ] spamming the invest button should update the animation and income in an instant

## Tasks

- [ ] write tests
- [ ] write a `PopupText` component
- [ ] give it the current `income` value of the parent element
- [ ] display this value and animate it a little bit for now
- [ ] handle logic when its being generated and when it should disappear again
- [ ] tweek animation timings and when to show

## Complexity Weight

3
