### ISSUE TITLE
US11 - Apply Invest Milestone after ProgressBar finished

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#19]
## Value Proposition

As a developer,
I want to ensure that my user always has correct visual feedback of the progress filling
so that my user feels more satisfaction and isn't getting confused

## Description

There is a bug, that if you reach a current milestone on a tier (ex. 15/15 -> 15/30) while the corresponding ProgressBar is active, the Bar jumps into a wrong position, or disappears at all. But the income and the button becomes available again later and since you have no visual feedback, you dont know when.

I want to fix that with following approach:

![Image](https://user-images.githubusercontent.com/109807794/230622750-e12871d2-d971-4f50-84a1-ef84a37e382a.png)

## Acceptance Critera

- [ ] The current bar of a tier must not be interrupted by a speed upgrade
- [ ] If an investment was applied and the income increased, the updated income should be applied when the bar finishes
- [ ] The speed upgrade should only apply after the bar has finished filling when a milestone is reached

## Tasks

- [ ] refactor money button logic into zustand store
- [ ] make sure state changes are in logical order, refactor if neccessary
- [ ] for the `ProgressBar` component, only apply inputted `delay` value inserted into the animation, when is `isFilling` state changes.

## Complexity Weight

3
