### ISSUE TITLE
money button

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#2]
## Value Proposition

As a User
I want to increase my game money by clicking a button
so that I can make progress in the game

## Description

![Image](https://user-images.githubusercontent.com/109807794/229279103-797a86de-2aa4-4277-9532-34403a6d5413.png)

## Acceptance Critera

- [ ] display a clickable button
- [ ] clicking does add game money
- [ ] updates the displayed money

## Tasks

- [ ] write tests
- [ ] create a `AddMoneyButton` component
- [ ] write a `handleAddMoney` function, which adds money to `MoneyDisplay`
- [ ] use a fixed number gain for now
- [ ] make the function available for the button component

## Complexity Weight

1

**Comment by rabe200** [comment]
lgtm!
