### ISSUE TITLE
US12 - current bar speed indicator

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#21]
## Value Proposition

As a user
I want visual feedback on how much the bar filling speed increased
so I know which tier has how many milestones reached

## Description

I want to add a :star: for each reached Milestone on a Tier.

![Image](https://user-images.githubusercontent.com/109807794/230714707-3f0feb95-2971-4003-bcbc-7412706132aa.png)

## Acceptance Critera

- [ ] Display 0 :star: if no milestone is reached (first Milestone after 10 x Investbutton)
- [ ] Display 1 :star: if first milestone is reached on a tier
- [ ] Display correct amount :star: depending on how many milestones reached

## Tasks

- [ ] write test, that star component is being rendered on milestone condition
- [ ] import & style star.svg as webpack component
- [ ] write conditional statement how many stars should be rendered, based on milestones reached of current tier

## Complexity Weight

2

**Comment by rabe200** [comment]
lgtm!
