### ISSUE TITLE
US14 - autoclicker

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#24]
## Value Proposition

As a user
I want an upgrade, which auto-clicks buttons for me
so that I dont have to push too many buttons all the time

## Description

![Image](https://user-images.githubusercontent.com/109807794/230721292-170861e2-610c-447d-8723-25b813e26d72.png)

## Acceptance Critera

- [ ] If manager button for a tier is being pushed, the money button is disabled for the user
- [ ] and the bar of the tier fills automaticly
- [ ] and the manager button becomes disabled
- [ ] if the automated bar finished filling, money is still being applied correctly
- [ ] manager button has a price, it should only be purchasable if enough money

## Tasks

- [ ] write test for `ManagerButton` is being rendered
- [ ] add `hasManager` boolean state to zustand store tiers array
- [ ] create a `ManagerButton` component with `currentTierId` prop
- [ ] Insert a purchase logic, so it's only available if enough money and only once
- [ ] write an automated handler, which triggers on the `onTimerEnd` state function of the current tier, it should retrigger the `clickTimer` function in state
- [ ] test with recursion, make sure to have the loop persistent and correctly, add exit cases and `clearTimeout`

## Complexity Weight

5
