### ISSUE TITLE
US15 - anticheat for clickermacro

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#25]
## Value Proposition

As a Developer
I want to avoid auto-clicking tools & macros
so that I can ensure competitive integrity

## Description

Currently, when operating on lower tiers with a significantly low delay value, reaching higher milestones results in an almost instantaneous filling process. However, this can be prevented by limiting the maximum decrease in delay, as long as no game auto-clicker is being used.

## Acceptance Critera

- [ ] The ProgressBar's filling speed must not exceed 500 milliseconds.
- [ ] Pressing the Wordpress button should not provide an instant reward-like feeling.

## Tasks

- [ ] Insert limiting logic into the `invest` function from the zustand state store

## Complexity Weight

1

**Comment by Stephan-mit-Ph** [comment]
Josh ausser rand und band 😂
