### ISSUE TITLE
US16 - income per second switch

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#27]
## Value Proposition

As a user
I want a simplified and streamlined way of tracking my income in the game
so that I can focus on the gameplay without feeling overwhelmed by constant visual updates. 

## Description

![Image](https://user-images.githubusercontent.com/109807794/230784532-a05ead99-b12c-415f-9ee4-6d5ecf648710.png)

## Acceptance Critera

- [ ] If enough milestones reached the income display should switch to a "Number/sec" view
- [ ] The Money button should be then disabled
- [ ] Money should be ticking up associated to its per second value
- [ ] Progress bar should stay filled 100%

## Tasks

- [ ] Check if `delay` of tier is below or equal to 500 and if `hasManager` is true, set new value `isPerSecond` to true then
- [ ] If `isPerSecond` is true disable the `clickTimer` function and associated button for this tier
- [ ] Create a Ticking function, which ticks for every 500ms and adds money in state, for tiers which unlocked `isPerSecond`
- [ ] Make sure Ticking function is persistent and scalable with other future tiers, which don't have `isPerSecond` booleans true for now

## Complexity Weight

5

**Comment by rabe200** [comment]
LGTM
