### ISSUE TITLE
US17 - svg logos to tiers

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#28]
## Value Proposition

As a User
I want to see different Product Logos on each tier
so that I get a better immersion into the lore

## Description

Plain text is boring, let the Money Buttons of each tier have their own logos!

## Acceptance Critera

- [ ] Each tier money button, should have its associated Logo rendered
- [ ] The Logos should feel scaled and placed equally

## Tasks

- [ ] add and refine stack logo svg's to project assets folder
- [ ] create `MoneyButtonLogo` component and give it `currentTierId` prop
- [ ] import all available stack logo svg's and create a selector logic function, which renders correct logo by currenTier

## Complexity Weight

1

**Comment by augustinanders** [comment]
LGTM but one suggestion: you could add wireframes so others can get a better idea of what you are doing.

**Comment by DominicWebDev** [comment]
already addicted, where can i sign in for beta? :>

LGTM
