### ISSUE TITLE
US18 - Milestone Progressbar

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#29]
## Value Proposition

As a user
I want visual cues that show me when I'm close to reaching the next milestone in the game
so I can easily compare my progress between tiers and stay motivated. 

## Description

Add a progress bar, which reflects state upon reaching next milestone

![Image](https://user-images.githubusercontent.com/109807794/230782576-2abf0ddf-9301-42b9-9323-f061eca63300.png)

## Acceptance Critera

- [ ] Display a Progress bar below the `number / number` layer, which updates with hitting the invest button
- [ ] If Milestone is reached, progress bar should reset to nothing (progress bar not visible)
- [ ] Milestone Progress bar should fill up again on the next Milestone cycle

## Tasks

- [ ] translate a value which counts from `from 0% to 100%` corresponding to `Milestone - previousMilestone`
- [ ] put that value into the tier state store
- [ ] visually update a progress bar with css, based on translated percentage value
- [ ] handle 100% correctly -> on finish, it should be visually resetted

## Complexity Weight

3

**Comment by augustinanders** [comment]
LGTM! very nice design in your Wireframe!
