### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#3]
## Value Proposition

As a Developer
I want to have a readme.md in my repository
so that visitors see what my app does

## Acceptance Critera

- [ ] create readme.md
- [ ] keep readme.md up to date
- [ ] a reader should be able to describe my app now

## Tasks

- [ ] create readme.md
- [ ] update readme.md to current version

## Complexity Weight

1
