### ISSUE TITLE
US19 - Navigation

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#30]
## Value Proposition

As a user
I want to navigate between different pages
so I can enter from a home screen, into different floors of the game and settings

## Description

![Image](https://user-images.githubusercontent.com/109807794/230787852-25e894cc-06c2-41f9-b509-2340d3b3d588.png)

![Image](https://user-images.githubusercontent.com/109807794/230787878-b0510a05-2b92-48c6-a96e-bb117790400c.png)

## Acceptance Critera

- [ ] App should start now from a home screen with the title of the game and a big enter button
- [ ] Hitting enter, should lead to the first floor, where the game is starting
- [ ] Going "upstairs" should eventually lead to reaching the "Boss Floor" page
- [ ] Correct and meaningful URL text should be displayed in the browser search bar

## Tasks

- [ ] Move current `Index` to `/[slug]`
- [ ] Create `Navigation` component, give it `currentFloor` prop
- [ ] Render 2 route buttons `downstairsButton` and `upstairsButton` within the new component
- [ ] let them route to floor-`[slug]`, handle a logic: `currentFloor +/- 1`
- [ ] if lowest slug reached, disable `downstairsButton`
- [ ] if highest slug reached let `upstairsButton` route to /bossfloor
- [ ] if /bossfloor disable `upstairsButton` and let `downstairsButton` route to highest [slug]
- [ ] !!! test how the behaviour of running progress bars is, while switching pages !!!

## Complexity Weight

3

**Comment by rabe200** [comment]
i like the meaningful url part. LGTM!
