### ISSUE TITLE
US20 - Boss Floor

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#31]
## Value Proposition

As a User
I want to have a page with my user settings
so I can customize my experience

## Description

![Image](https://user-images.githubusercontent.com/109807794/230789112-692359a5-d5ff-48aa-9e9a-d1f63aa8e290.png)

## Acceptance Critera

- [ ] Have a form input, which displays my current Username
- [ ] Type something into the form input, if hit submit it should update the Username on all pages

## Tasks

- [ ] Create a form
- [ ] Create a submit button
- [ ] handle Form logic and write form.data into Zustand store
- [ ] insert store data everywhere, where userName is being displayed

## Complexity Weight

1
