### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#4]
## Value Proposition

As a User
I want to get my game money added after a short delay
so it feels more rewarding

## Description

![Image](https://user-images.githubusercontent.com/109807794/229285018-69eb136a-f99d-4f85-9583-1bdb245cc971.png)

## Acceptance Critera

- [ ] after the add money button is pressed the money should be added with a delay
- [ ] add money button is disabled while delay isn't completed
- [ ] display a progress bar that fills up corresponding to the set delay
- [ ] reset progress bar after delay is completed
- [ ] make current income visible

## Tasks

- [ ] write tests
- [ ] create a `ProgressBar` component with a `delay` and `income` prop
- [ ] display income value
- [ ] on button press add filling animation related to `delay` value to `ProgressBar`
- [ ] disable button while filling takes place
- [ ] run `addMoney` when filling finished
- [ ] reset filling animation & enable button

## Complexity Weight

3

**Comment by toshydev** [comment]
Shweet, LGTM
