### ISSUE TITLE
US21 - Login

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#42]
## Value Proposition

As a user
I want to have a personal account
so that I have an unique identity playing the game

## Description

Users do need an personal account, so they can have their own game progress. Since the app should be a block-chain game, it only makes sense to have a web3 login. No google, no Github, no facebook ... only wallet logins. In future Development, the wallet accounts are being used to get the users game-data saved in a cloud database.

![Image](https://user-images.githubusercontent.com/109807794/232404449-3ea700d0-7978-49f1-98c8-916130221804.png)

## Acceptance Critera

- [ ] When opening the app while not being logged in, it should show a Wallet Login Button
- [ ] You should be able to login with a "Metamask"-Wallet
- [ ] If logged in, it should display your wallet public address

## Tasks

- [ ] Use a library for login handling
- [ ] Create some test login accounts, for debugging and for the QA people
- [ ] Create API to fetch authentication in the Backend
- [ ] Display available wallet data

## Complexity Weight

5

**Comment by salaos** [comment]
Looks good! Just one thing: maybe specify the error messages that should be displayed if the user enters incorrect login credentials.
