### ISSUE TITLE
US22 - Savegame

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#43]
## Value Proposition

As a user
I want to save my game progress
so I can continue playing the game any time at my current progress

## Description

Right now you reset the game and you lose all your progress. The current Game State, e.g. Save File should be saved. And also be able to recall again.

## Acceptance Critera

- [ ] In the game is a Savegame button now on the Bossfloor (last floor)
- [ ] This button should save your game and also respond visually that it's saving
- [ ] Reloading the game, should load your current Savegame

## Tasks

- [ ] write save and load functions in store
- [ ] create buttons which handels those function
- [ ] bring in hooks, where such functions getting booted up

## Complexity Weight

5

**Comment by salaos** [comment]
Don't know about the security but for first step it will work I guess :)
Maybe Include edge case, such as what happens if the database connection is lost or if the user tries to access someone else's save game data.
