### ISSUE TITLE
US23 - Autosave

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#44]
## Value Proposition

As a user
I want to have autosave
so that I don't have to save my game progress manually

## Description

The Savegame-button was for debugging and functional testing. Now it's time for autosaving in an interval. 

## Acceptance Critera

- [ ] After I played the game for a minute with my personal account my game progress should reappear after reload

## Tasks

- [ ] Set a timing function, which uses the current read/write logic
- [ ] Think about performance and about DB writing times
- [ ] Limit API Requests of a single user and timeout spammed requests, make fixed interval timing slots, so if user tries to manipulate application timings to cheat, it's getting detected directly
- [ ] Implement a timeout case and leave a trigger function open for penalty handling

## Complexity Weight

2

**Comment by salaos** [comment]
Cool! Some thoughts:
- consider providing user feedback (display a message or an icon to indicate to the user that the autosave feature is enabled and working)
- what saving interval is optimal?
