### ISSUE TITLE
US24 - Idle Money

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#45]
## Value Proposition

As a User
I desire to make progress in the game even when I am not actively playing
allowing the game to have a genuine idle feature

## Description

![Image](https://user-images.githubusercontent.com/109807794/232413958-c3deff20-7ba2-42ee-9e28-fee1b21cfde1.png)

## Acceptance Critera

- [ ] If game is closed for more than a minute, reopening should apply money
- [ ] The amount of money should be the amount which active managers gained in all tiers over the idle time
- [ ] The Idle money should be displayed in a prompt, where you see its amount

## Tasks

- [ ] Write a function on load, which calculates from previous tiers the `incomePerSecond` value, when `hasManager` is true
- [ ] Make function logic based on time passed
- [ ] Make sure timing functions run on server side, so the client can't cheat time
- [ ] Have a savestate timestamp in Database in UNIX-Format

## Complexity Weight

5

**Comment by salaos** [comment]
LGTM!
