### ISSUE TITLE
US25 - Shorten Large Numbers

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#48]
## Value Proposition

As a user
I want to see large numbers in a more easily readable format, such as 100 million instead of 100000000, 
so that I can quickly and accurately interpret my current amount of money

## Description

![Image](https://user-images.githubusercontent.com/109807794/232848435-2db82666-35d6-4481-ab92-2d903977eea3.png)

## Acceptance Critera

- [ ] If numbers go beyond 1.000.000,00 it should display 1,000 million instead
- [ ] If numbers go beyond 1.000 million it should display 1,000 billion instead and so on

## Tasks

- [ ] Update the numeric converter, so it handles display of larger numbers
- [ ] Convert Number to string
- [ ] Create switch cases on certain string lengths
- [ ] Create a util.js file, and put that converter there, so its reusable
- [ ] Apply converter where it is needed and also think of different styles based on font scalings

## Complexity Weight

3

**Comment by toshydev** [comment]
Yes, let's stop counting pennies! How about scientific notation? 🫠
`6.72×10**86` ✅

**Comment by Satttoshi** [comment]
Thats for nerds :p
