### ISSUE TITLE
invest button

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#5]
## Value Proposition

As a User
I want to spend money to upgrade my income
so my money has purpose

## Description

![Image](https://user-images.githubusercontent.com/109807794/229342340-04f4a74c-e463-4e54-9e65-4753982a61be.png)

## Acceptance Critera

- [ ] display a invest button, with name and price
- [ ] if pressed, it should increase the income value displayed on the progress bar
- [ ] it should also remove money equal to its displayed price
- [ ] after each button press, the price should accumulate

## Tasks

- [ ] write tests
- [ ] create a `ProgressBar` component with a `delay` prop
- [ ] on button press add filling animation related to `delay` value to `ProgressBar`
- [ ] disable button while filling takes place
- [ ] run `addMoney` when filling finished
- [ ] reset filling animation & enable button

## Complexity Weight

1

**Comment by louisweiser** [comment]
It's very detailed, I could implement the task. very well.
