### ISSUE TITLE
US26 - Scaling 2

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#50]
## Value Proposition

As a gamer
I want to enjoy a more rewarding and engaging experience through meaningful scaling
so that each unlocked tier offers equal benefits and allows me to progress fairly and enjoyably through the game

## Description

![Image](https://user-images.githubusercontent.com/109807794/230086975-5383a51f-4c30-4386-b22c-a6d24d73a676.png)

## Acceptance Critera

- [ ] Scaling should "feel" nice
- [ ] Your focus on which product is worth investing in, is switching based on reached Milestones
- [ ] Wordpress Sites should feel worth it at later stages of the game aswell

(hint/help for QA: you can cheat money with hitting space)

## Tasks

- [ ] Get a coffee
- [ ] Improve current scaling maths
- [ ] Add different scaling to Milestones Speed dividers

## Complexity Weight

3
