### ISSUE TITLE
US27 - Tier Production Timer

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#51]
## Value Proposition

As a User
I want to see a timer, when the bar filling is being finished
So that I have a better track of a tiers progress, escpecially when the timer is very long.

## Description

![Image](https://user-images.githubusercontent.com/109807794/233138170-4b4e5957-9e28-4051-9c5b-e52eb9ac1227.png)

## Acceptance Critera

- [ ] Display a timer on each tier, which shows the time and ticks down to 0 when button is being pressed
- [ ] If value is per second, show a rocket instead (Wordpress Website on level 25 for ex.)

## Tasks

- [ ] Write a timing state function in zustand store
- [ ] Run an interval until set state timer finished
- [ ] Make sure to handle clearing intervals correctly
- [ ] Make sure to sync timing with Progress Bar (this might not be 100% possible yet when pages has been switched)

## Complexity Weight

3

**Comment by ella-blaupause** [comment]
LGTM 👍
