### ISSUE TITLE
US28 - Hire Managers Menu

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#53]
## Value Proposition

As a User
I want to select Managers in a "job interviews" menu
so that hiring a manager fits more into the lore

## Description

![Image](https://user-images.githubusercontent.com/109807794/233629903-b4bfe62b-008b-474d-aaea-fda6be4049cb.png)

## Acceptance Critera

- [ ] Navigate to the Boss Floor and you do find a "Jobs Interview" Button
- [ ] Pushing the button opens the Applications Modal
- [ ] You can Hire Managers of unlocked Tiers here.
- [ ] You can switch in between Manager Applications
- [ ] It should show a fitting application and the corresponding Logo of its tier
- [ ] Hire should be disabled if not enough money

## Tasks

- [ ] Move Logic and Hire menu to Boss Floor Component Page
- [ ] Create a Modal, which triggers when "Jobs Interview" Button is pressed
- [ ] Handle Modal opening and closing logic
- [ ] Render Content based on current Tier.
- [ ] Only display content of unlocked Tiers
- [ ] Remove content if manager was hired already
- [ ] Make sure the function logic behind managers still work

## Complexity Weight

3

**Comment by Stephan-mit-Ph** [comment]
Herby❤️
