### ISSUE TITLE
US29 - Tutorial

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#55]
## Value Proposition

As a User
I want an interactive game tutorial
so that I gain a clear understanding of how to play

## Description

![Image](https://user-images.githubusercontent.com/109807794/233775151-2660a767-f68b-4998-b557-b4b8c8258c1b.png)

## Acceptance Critera

- [ ] When starting the game for the first time, page should be dimmed out and the Wordpress Button highlighted
- [ ] A explanation text should be next to it
- [ ] The same should happen if enough money for the first invest

## Tasks

- [ ] Write tutorial states into zustand store
- [ ] Create a TutorialModal component, render it on top of the slug page
- [ ] Write z-index logic into the components, so the buttons come ontop of the modals
- [ ] Add an explanation box with meaningful explanations
- [ ] Add logic to close the Modal if a button was pressed

## Complexity Weight

4

**Comment by WE-dev1** [comment]
LGTM!
