### ISSUE TITLE
US6 - investment milestones

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#6]
## Value Proposition

As a User
I want to have macro based goals
so my game experience has more depth

## Description

When you press the Investment button, a counter will increase. When the counter reaches a specific milestone, a new milestone number will be displayed. Once a milestone is reached, the progress bar will fill up faster.

![Image](https://user-images.githubusercontent.com/109807794/229360112-99f964d5-3595-42a0-bbfb-dd5bc3e0ab5e.png)

## Acceptance Critera

- [ ] display a milestone
- [ ] milestone counter is increasing by pressing the investment button
- [ ] if milestone is reached, it should display a new milestone & increase the speed of the progress bar

## Tasks

- [ ] write tests
- [ ] create a `Milestones` component
- [ ] let it have the props `investementCount`
- [ ] write a function `handleMilestone`, which runs when `currentMilestone` is reached
- [ ] display current `investmentCount` and the `currentMilestone`
- [ ] let `handleMilestone` decrease the `delay` value in the `ProgressBar` component & adjust `currentMilestone` to a new value in predetermined steps

## Complexity Weight

3

**Comment by Kevinwey** [comment]
LGTM! easy to understand :)
