### ISSUE TITLE
US30 - Unlock Floors

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#61]
## Value Proposition

As a user
I want to unlock new floors
so that I can explore new areas of the game

## Description

At the beginning we're on playing 5 product tiers, unlocking more tiers requiring to unlock another floor. Which improves the expression of the boss company lore.

![Image](https://user-images.githubusercontent.com/109807794/235008406-299e03f8-59a3-476b-8573-964dbc145c08.png)

## Acceptance Critera

- [ ] When going upstairs, you find a "construct floors" button
- [ ] If you have enough money, you can build new floors there
- [ ] If you don't have enough money, you cannot build floors there and the buy button is greyed out
- [ ] If a floor was builded, you can access it now by going downstairs and upstairs
- [ ] You should be able to navigate within the displayed house on the modal
- [ ] The Highest floor should always be the "boss floor"

## Tasks

- [ ] do some wyld magic

## Complexity Weight

3

**Comment by WE-dev1** [comment]
LGTM!😇
