### ISSUE TITLE
US32 - overall money/sec

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#67]
## Value Proposition

As a User
I want to see my overall money per second income
so that I gain more information about my general game progress

## Description

Suggested Feature, makes alot of sense to put it into the boss floor, where you can check your overall companies income.

## Acceptance Critera

- [ ] See money per second value in the boss floor

## Tasks

- [ ] Get current tier incomePerSecond values together and display them in a new component
- [ ] Use that component in the boss floor
- [ ] incomePerSecond function only run when a manager is hired, make the state update on every invest function run

## Complexity Weight

1
