### ISSUE TITLE
US7 - render more tier buttons

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/idle-boss#7]
## Value Proposition

As a User
I want to click more than one button
so I can enjoy pushing multiple buttons

## Description

![Image](https://user-images.githubusercontent.com/109807794/230020411-2c2d24ee-c3e8-4527-971e-bd23dc06d55a.png)

## Acceptance Critera

- [ ] display multiple sections with money button, progress bar, investment button and milestone display
- [ ] populated elements should be all functional

## Tasks

- [ ] write tests
- [ ] duplicate `Product` component within `Index` and only give it the prop `tier`
- [ ] loads props corresponding to current tier, use these scaled values and renders components `moneyButton` `progressBar` `investmentButton` `Milestones` within section
- [ ] implement simple tier scaling in Zustand store for now

## Complexity Weight

2

**Comment by ChristophObst** [comment]
lgtm
